name: Linux, gcc, EDK2

on:
  workflow_dispatch:

env:
  COMPILER: GCC5
  GCC5_AARCH64_PREFIX: aarch64-linux-gnu-
  GCC5_RISCV64_PREFIX: riscv64-linux-gnu-
  GCC5_LOONGARCH64_PREFIX: loongarch64-unknown-linux-gnu-
  FULL_SHELL_GUID: EA4BB293-2D7F-4456-A681-1F22F42CD0BC
  BUILD_TYPES: DEBUG RELEASE
  ARCHS: X64 IA32 AARCH64 RISCV64 LOONGARCH64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      # Must happen first, else the LoongArch toolchain gets deleted (even with clean: false)
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Install toolchains
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install gcc-12-multilib gcc-12-aarch64-linux-gnu gcc-12-riscv64-linux-gnu nasm uuid-dev
        sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
        sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-ar-12 /usr/bin/aarch64-linux-gnu-gcc-ar
        sudo ln -s /usr/bin/riscv64-linux-gnu-gcc-12 /usr/bin/riscv64-linux-gnu-gcc
        sudo ln -s /usr/bin/riscv64-linux-gnu-gcc-ar-12 /usr/bin/riscv64-linux-gnu-gcc-ar
        curl -L -O https://github.com/loongson/build-tools/releases/download/2025.08.08/x86_64-cross-tools-loongarch64-binutils_2.45-gcc_15.1.0-glibc_2.42.tar.xz
        tar -xJf x86_64-cross-tools-loongarch64-binutils_2.45-gcc_15.1.0-glibc_2.42.tar.xz
        echo "$PWD/cross-tools/bin" >> "$GITHUB_PATH"

    - name: Set up EDK2
      run: make -C edk2/BaseTools

    - name: Build UEFI binaries
      run: |
        cd edk2
        source edksetup.sh
        for BUILD_TYPE in ${{ env.BUILD_TYPES }}; do
          for ARCH in ${{ env.ARCHS }} ; do
            build -a $ARCH -b $BUILD_TYPE -t ${{ env.COMPILER }} -p ShellPkg/ShellPkg.dsc --pcd gEfiShellPkgTokenSpaceGuid.PcdShellScreenLogCount=8
          done
        done

    - name: Create individual Shell binaries
      run: |
        for ARCH in ${{ env.ARCHS }}; do
          cp edk2/Build/Shell/RELEASE_${{ env.COMPILER }}/$ARCH/Shell_${{ env.FULL_SHELL_GUID }}.efi ./shell${ARCH,,}.efi
        done
        if [ -f ./shellaarch64.efi ]; then
          mv ./shellaarch64.efi ./shellaa64.efi
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        path: ./*.efi
